Possiblity to run with "ignoreLocality" option

diff --git a/filelist b/filelist
--- a/filelist
+++ b/filelist
@@ -14,12 +14,17 @@ if [ -z "$dataset" ]; then
 	exit 1
 fi
 
-das_client --query="site dataset=$dataset" | grep $site -q  || {
-	echo "[ERROR `basename $0`] dataset $dataset not at $site" >> /dev/stderr
-	das_client --query="site dataset=$dataset" >> /dev/stderr
-	exit 1
-}
-
+case $site in 
+	any)
+		;;
+	*)
+		das_client --query="site dataset=$dataset" | grep $site -q  || {
+			echo "[ERROR `basename $0`] dataset $dataset not at $site" >> /dev/stderr
+			das_client --query="site dataset=$dataset" >> /dev/stderr
+			exit 1
+		}
+		;;
+esac
 
 if [ -n "$runrange" ];then
 	runmin=`echo $runrange | cut -d '-' -f 1`
